### ISSUE TITLE
Broken release 1.1.0

### ISSUE THREAD

**Issue by lewis-fidlers** [Yummygum/react-flagpack#40]
## Please check all that apply

- [ ] visual bug
- [ ] functional bug
- [x] able to consistently reproduce

## Current Behavior
When Installed through `npm install react-flagpack --save`
 - In a clean create react app (v17) empty flags are shown
 - In a react 16.8 or higher existing app using a flag components crashes the app (quite a big app with webpack which i think actually causes the crash)
 - in a clean create-react-app with react v16.x a blank flag is shown as well (step 4 in steps to reproduce)
 
## Possible Solution
Seems like 1.1.0 was released yesterday, which is not tagged as the current release. It is installed through npm though when no version is specified.

So the easy fix is probably not making the 1.x branches available for now :)

## Steps to Reproduce

1. `npx create-react-app my-app`
2. `npm i react-flagpack`
3. add ```jsx
<Flag
  code="NL"
  gradient="real-linear"
  size="m"
  hasDropShadow
/>``` 
to the clean app
4. a empty flag is shown: 
![image](https://user-images.githubusercontent.com/8747225/127494091-32158d43-4281-4392-8fa3-a78e14d8e1b5.png)

**Comment by mrzlab630** [comment]
same problem

**Comment by andrepadeti** [comment]
same here as well

**Comment by daoneandonly** [comment]
While we still have some issues with `react-flagpack`, I've tested the latest build with an `create-react-app` and it rendered a Flag correctly. Can you confirm this issue has been solved?

**Comment by zoeyfrisart** [comment]
Hi all, this should now be resolved, in case you're still facing issues after upgrading to Version 2.0.2, please open up a new issue 🙏
