### ISSUE TITLE
Flagpack not loading into NextJS

### ISSUE THREAD

**Issue by daoneandonly** [Yummygum/react-flagpack#47]
## Please check all that apply

- [x] functional bug

## Current Behavior
Currently the project doesn't work with [NextJS](https://nextjs.org/). It does work however with a `create-react-app`.

## Possible Solution

* A possible solution is adding a ESM file to the exports through rollup.
* Removing the `type: "module"` from the `package.json` also stops the project from crashing altogether, however the flag still doesn't render.

## Logs
![image](https://user-images.githubusercontent.com/14161179/133438974-0bfae6a6-cdee-4ebb-9a3d-0520fb7dc42b.png)

Related to issues #46, #45

**Comment by Titou325** [comment]
Hello!

It seems that this error is also affecting Gatsby, which does not provide any way to call `require` from imported CommonJS modules.

In the meantime, I am using [patch-package](https://www.npmjs.com/package/patch-package) to replace `"type": "module"` with `"type": "commonjs"`.

I think this change could easily be implemented without breaking the current setup.

Have a nice day

**Comment by tjablonski** [comment]
Hello,
i have similar problem importing `react-flagpack` with storybook, when i try to use Flag component in my Country component, it shows `Unexpected error while loading ./components/Country/Country.stories.tsx: ReferenceError: require is not defined` in console. My component dissapear from storybook components list.

**Comment by yotam707** [comment]
any update on this bug, the fix is simple

**Comment by vrushank** [comment]
It should be a great addition. Many of us are waiting to implement it with NextJS.

**Comment by mbale** [comment]
https://github.com/mbale/react-flagpack

There's a nextjs branch if you cannot wait for the PR.

Tested with v12

**Comment by donovanroubos** [comment]
@mbale Is this fix also compatible with other React platforms (SB, CRA, Next JS, etc.). If yes, could you maybe create a PR for this fix? Would be awesome 🙆‍♂️.

**Comment by intensr** [comment]
still on it ?

**Comment by ethanmick** [comment]
Is there any timeline on when this will be resolved?

**Comment by digitaltim-de** [comment]
Same error

**Comment by LeakedDave** [comment]
```
/** @type {import('next').NextConfig} */
const withTM = require('next-transpile-modules')(['@stampmyvisa/react-flagpack']);

module.exports = withTM({
    trailingSlash: false,
    output: "export",
    images: { unoptimized: true },
    webpack: (config, { isServer }) => {
        config.module.rules.push({
            test: /\.svg$/,
            include: /node_modules\/@stampmyvisa\/react-flagpack\/dist\/flags/,
            use: [
                {
                    loader: 'file-loader',
                    options: {
                        name: '[path][name].[hash].[ext]', // Update this line
                        outputPath: 'static/flags/',
                        publicPath: '/_next/static/flags/',
                        emitFile: !isServer,
                    },
                },
            ],
        });

        return config;
    },
})
```

This is a fix for NextJS that I'm using

**Comment by zoeyfrisart** [comment]
Hi all, this should now be resolved, in case you're still facing issues after upgrading to Version 2.0.2, please open up a new issue 🙏
