### ISSUE TITLE
Broken on React 18

### ISSUE THREAD

**Issue by scott-cornwell** [Yummygum/react-flagpack#69]
Dependencies do not allow for React 18 and also require statement is used causing complete failure to compile in a standard create react app setup.

**Comment by donovanroubos** [comment]
Hi @scott-cornwel, thanks for creating this issue.

As you could imagine, Yummygum is an agency where we're fully focussing on our client projects at this moment. We do not have any expecting plans in Q1 right now to revive the Flagpack project. We suppose to pickup the project in Q2 again and come with a solution to let Flagpack also work on React 18 versions!

**Comment by acron0** [comment]
Any update?

**Comment by Feridinha** [comment]
Any... Updates... ?

**Comment by viktorbasta** [comment]
any updates?
