### ISSUE TITLE
Require isn't defined

### ISSUE THREAD

**Issue by Abdulrahim2567** [Yummygum/react-flagpack#70]
installed the package and included it in my NextJS 13 project but the browser threw an error message during runtime with thee following error;
**Unhandled Runtime Error**
 `ReferenceError: require is not defined`
**Call Stack**
`unknown`
`node_modules\.pnpm\react-flagpack@1.2.0_react@18.2.0\node_modules\react-flagpack\dist\react-flag-rollup.cjs.js (1:13)`

**Comment by fitzgibbonjack** [comment]
Same here

**Comment by rhys-saunders** [comment]
Getting the same issue

**Comment by dgastudio** [comment]
same here

**Comment by acron0** [comment]
Same here

**Comment by beeera** [comment]
This works for me, as a quick fix:

`yarn add react-flagpack@v1.1.0`

**Comment by oscarteston-eb** [comment]
Hello. Same here. 
It is happening because the library exposes a CommonJS module `react-flag-rollup.cjs.js`
, however in the package.json it indicates `type:module` which supports ES modules but not CommonJS modules
